<a href="https://colab.research.google.com/github/rahiakela/generative-adversarial-networks-with-python/blob/part-1-foundations/1_upsampling_and_transpose_convolutional_for_generative_adversarial_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Upsampling and Transpose Convolutional  for Generative Adversarial Networks

The GAN architecture is comprised of both a generator and a discriminator model. The generator is responsible for creating new outputs, such as images, that plausibly could have come from the original dataset. The generator model is typically implemented using a deep convolutional neural network and
results-specialized layers that learn to fill in features in an image rather than extract features from an input image.

Two common types of layers that can be used in the generator model are a upsample layer that simply doubles the dimensions of the input and the transpose convolutional layer that performs an inverse convolution operation.

In this notebook, we will discover how to use Upsampling and Transpose Convolutional Layers in Generative Adversarial Networks when generating images. 

After completing this guide, we will know:

* Generative models in the GAN architecture are required to upsample input data in order to generate an output image.

* The Upsampling layer is a simple layer with no weights that will double the dimensions of input and can be used in a generative model when followed by a traditional convolutional layer.

* The Transpose Convolutional layer is an inverse convolutional layer that will both upsample input and learn how to fill in details during the model training process.

## Setup

In [0]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
    IS_COLAB = True
except Exception:
    IS_COLAB = False

# TensorFlow ≥2.0 is required
import tensorflow as tf
from tensorflow import keras
assert tf.__version__ >= "2.0"

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import UpSampling2D, Dense, Reshape, Conv2D, Conv2DTranspose

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)
tf.random.set_seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

## Need for Upsampling in GANs

Generative Adversarial Networks are an architecture for neural networks for training a generative model. The architecture is comprised of a generator and a discriminator model, each of which are implemented as a deep convolutional neural network. 

The discriminator is responsible for classifying images as either real (from the domain) or fake (generated). 

The generator is responsible for generating new plausible examples from the problem domain. The generator works by taking a random point from the latent space as input and outputting a complete image, in a one-shot manner.

A traditional convolutional neural network for image classification, and related tasks, will use pooling layers to downsample input images. For example, an average pooling or max pooling layer will reduce the feature maps from a convolutional by half on each dimension, resulting in an output that is one quarter the area of the input. 

Convolutional layers themselves also perform a form of downsampling by applying each filter across the input images or feature maps; the resulting activations are an output feature map that is smaller because of the border effects.
Often padding is used to counter this effect. 

The generator model in a GAN requires an inverse operation of a pooling layer in a traditional convolutional layer. It needs a layer to translate
from coarse salient features to a more dense and detailed output.

A simple version of an unpooling or opposite pooling layer is called an upsampling layer. It works by repeating the rows and columns of the input. A more elaborate approach is to perform a backwards convolutional operation, originally referred to as a deconvolution, which is incorrect, but is more commonly referred to as a fractional convolutional layer or a transposed
convolutional layer.

## How to Use the Upsampling Layer

Perhaps the simplest way to upsample an input is to double each row and column. 

For example, an input image with the shape 2 × 2 would be output as 4 × 4.

```python
input = [
  [1, 2],
  [3, 4]
]

Output = [
  [1, 1, 2, 2],
  [1, 1, 2, 2],
  [3, 3, 4, 4],
  [3, 3, 4, 4]
]
```

### Worked Example Using the UpSampling2D Layer

The Keras deep learning library provides this capability in a layer called UpSampling2D. It can be added to a convolutional neural network and repeats the rows and columns provided as input in the output.

**Step-1**

First, we can define a contrived input image that is 2 × 2 pixels. We can use specific values for each pixel so that after upsampling, we can see exactly what effect the operation had on the input.

**Step-2**

Once the image is defined, we must add a channel dimension (e.g. grayscale) and also a sample dimension (e.g. we have 1 sample) so that we can pass it as input to the model. The data dimensions in order are: samples, rows, columns, and channels.

**Step-3**

We can now define our model. The model has only the UpSampling2D layer which takes 2 × 2 grayscale images as input directly and outputs the result of the upsampling operation.

**Step-4**

We can then use the model to make a prediction, that is upsample a provided input image.

**Step-5**

The output will have four dimensions, like the input, therefore, we can convert it back to a 2 × 2 array to make it easier to review the result.

Tying all of this together, the complete example of using the UpSampling2D layer in Keras is provided below.

In [2]:
# step-1: define input data
X = np.array([
    [1, 2],
    [3, 4]          
])
print(X)

# step-2: reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))

# step-3: define model
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1)))
model.summary()

# step-4: make a prediction with the model
yhat = model.predict(X)

# step-5: reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d (UpSampling2D) (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


We can see that it will output a 4 × 4 result as we expect, and importantly, the
layer has no parameters or model weights. This is because it is not learning anything; it is just doubling the input. 

Finally, the model is used to upsample our input, resulting in a doubling of
each row and column for our input data, as we expected.

By default, the UpSampling2D will double each input dimension. This is defined by the size argument that is set to the tuple (2,2). You may want to use different factors on each dimension, such as double the width and triple the height. 

This could be achieved by setting the size argument to (2, 3). The result of applying this operation to a 2 × 2 image would be a 4 × 6 output image (e.g. 2 × 2 and 2 × 3).

In [3]:
# step-1: define input data
X = np.array([
    [1, 2],
    [3, 4]          
])
print(X)

# step-2: reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))

# step-3: define model
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1), size=(2, 3)))
model.summary()

# step-4: make a prediction with the model
yhat = model.predict(X)

# step-5: reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 6))
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]]


Additionally, by default, the UpSampling2D layer will use a nearest neighbor algorithm to fill in the new rows and columns. This has the effect of simply doubling rows and columns, as described and is specified by the interpolation argument set to ‘nearest’. 

Alternately, a bilinear interpolation method can be used which draws upon multiple surrounding points. This can be specified via setting the interpolation argument to ‘bilinear’.

In [4]:
# step-1: define input data
X = np.array([
    [1, 2],
    [3, 4]          
])
print(X)

# step-2: reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))

# step-3: define model
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1), size=(2, 3), interpolation='bilinear'))
model.summary()

# step-4: make a prediction with the model
yhat = model.predict(X)

# step-5: reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 6))
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_2 (UpSampling2 (None, 4, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1.        1.        1.3333334 1.6666667 2.        2.       ]
 [1.5       1.5       1.8333334 2.1666667 2.5       2.5      ]
 [2.5       2.5       2.8333335 3.1666667 3.5       3.5      ]
 [3.        3.        3.3333335 3.6666667 4.        4.       ]]


### Simple Generator Model With the UpSampling2D Layer

The UpSampling2D layer is simple and effective, although does not perform any learning. It is not able to fill in useful detail in the upsampling operation. To be useful in a GAN, each UpSampling2D layer must be followed by a Conv2D layer that will learn to interpret the doubled input and be trained to translate it into meaningful detail.

In this example, our little GAN generator model must produce a 10 × 10 image as output and take a 100 element vector of random numbers from the latent space as input. 

First, a Dense fully connected layer can be used to interpret the input vector and create a sufficient number of activations (outputs) that can be reshaped into a low-resolution version of our output image, in this case, 128 versions of a 5 × 5 image.

Next, the 5 × 5 feature maps can be upsampled to a 10 × 10 feature map.

Finally, the upsampled feature maps can be interpreted and filled in with hopefully useful detail by a Conv2D layer. The Conv2D has a single feature map as output to create the single image we require.

Tying this together, the complete example is listed below.

In [5]:
# define model
model = Sequential()

# define input shape, output enough activations for 128 5x5 image
model.add(Dense(128 * 5 * 5, input_dim=100))

# reshape vector of activations into 128 feature maps with 5x5
model.add(Reshape((5, 5, 128)))

# double input from 128 5x5 to 1 10x10 feature map
model.add(UpSampling2D())

# fill in detail in the upsampled feature maps and output a single image
model.add(Conv2D(1, (3, 3), padding='SAME'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_3 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


We can see that the Dense layer outputs 3,200 activations that are then reshaped into 128 feature maps with the shape 5×5. The widths and heights are doubled to 10×10 by the UpSampling2D layer, resulting in a feature map with quadruple the area. 

Finally, the Conv2D processes these feature maps and adds in detail, outputting a single 10 × 10 image.

## How to Use the Transpose Convolutional Layer

The transpose convolutional layer is more complex than a simple upsampling layer. A simple way to think about it is that it both performs the upsample operation and interprets the coarse input data to fill in the detail while it is upsampling. It is like a layer that combines the UpSampling2D and Conv2D layers into one layer. This is a crude understanding, but a practical starting point.

In fact, the transpose convolutional layer performs an inverse convolution operation. Specifically, the forward and backward passes of the convolutional layer are reversed.

Let’s make this concrete with an example. Consider an input image with the size 2 × 2 as follows:

```python

        1, 2
Input = 3, 4
```

Assuming a single filter with a 1 × 1 kernel and model weights that result in no changes to the inputs when output

```python

         1, 2
Output = 3, 4
```

With an output stride of (2,2), the 1 × 1 convolution requires the insertion of additional rows and columns into the input image so that the reads of the operation can be performed.

```python

        1, 0, 2, 0
Input = 0, 0, 0, 0
        3, 0, 4, 0
        0, 0, 0, 0
```

The model can then read across this input using an output stride of (2,2) and will output a 4 × 4 image, in this case with no change as our model weights have no effect by design:

```python

        1, 0, 2, 0
Output= 0, 0, 0, 0
        3, 0, 4, 0
        0, 0, 0, 0
```



### Worked Example Using the Conv2DTranspose Layer

Keras provides the transpose convolution capability via the Conv2DTranspose layer.

**Step-1**:First, we can define a contrived input image that is 2 × 2 pixels.

**Step-2**:Once the image is defined, we must add a channel dimension (e.g. grayscale) and also a sample dimension (e.g. we have 1 sample) so that we can pass it as input to the model.

**Step-3**:We can now define our model. The model has only the Conv2DTranspose layer, which takes 2 × 2 grayscale images as input directly and outputs the result of the operation. The Conv2DTranspose both upsamples and performs a convolution. Additionally, we must specify a stride of (2,2) because the upsampling is achieved by the stride behavior of the convolution on the input. Specifying a stride of (2,2) has the effect of spacing out the input.

**Step-4**:To make it clear what the Conv2DTranspose layer is doing, we will fix the single weight in the single filter to the value of 1.0 and use a bias value of 0.0. These weights, along with a kernel size of (1,1) will mean that values in the input will be multiplied by 1 and output as-is, and the 0 values in the new rows and columns added via the stride of 2 × 2 will be output as 0.

Tying all of this together, the complete example of using the Conv2DTranspose layer in Keras is provided below.



In [7]:
# Step-1 : define input data
X = np.array([[1, 2], [3, 4]])
print(X)

# Step-2: reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))

# Step-3: define model
model = Sequential()
model.add(Conv2DTranspose(1, (1, 1), strides=(2, 2), input_shape=(2, 2, 1)))
model.summary()

# Step-4 : define weights that they do nothing
weights = [np.array([[[[1]]]]), np.array([0])]
# store the weights in the model
model.set_weights(weights)

# make a prediction with the model
yhat = model.predict(X)

# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


We can see that it will output a 4 × 4 result as we expect, and importantly, the
layer two parameters or model weights. One for the single 1×1 filter and one for the bias. Unlike the UpSampling2D layer, the Conv2DTranspose will learn during training and will attempt to fill in detail as part of the upsampling process. Finally, the model is used to upsample our input.

In practice, we will use a large number of filters (e.g. 64 or 128), a larger kernel (e.g. 3 × 3, 5 × 5, etc.), and the layer will be initialized with random weights that will learn how to effectively upsample with detail during training. 

In fact, you might imagine how different sized kernels will result in different
sized outputs, more than doubling the width and height of the input. In this case, the padding argument of the layer can be set to ‘same’ to force the output to have the desired (doubled) output shape.

In [13]:
# Step-1 : define input data
X = np.array([[1, 2], [3, 4]])
print(X)

# Step-2: reshape input data into one sample a sample with a channel
X = X.reshape((1, 2, 2, 1))

# Step-3: define model
model = Sequential()
# using padding to ensure that the output are only doubled
model.add(Conv2DTranspose(1, (3, 3), strides=(2, 2), padding='SAME', input_shape=(2, 2, 1)))
model.summary()

# Step-4 : define weights that they do nothing
#weights = [np.array([[[[1]]]]), np.array([0])]
#print(weights.shape)
# store the weights in the model
#model.set_weights(weights)

# make a prediction with the model
yhat = model.predict(X)

# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_6 (Conv2DTr (None, 4, 4, 1)           10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
[[-7.4414134e-02  2.8711915e-02 -1.5258479e-01  5.7423830e-02]
 [-4.9986732e-01 -1.6379261e-01 -8.9213449e-01 -3.2758522e-01]
 [ 1.6900164e-01 -1.1338845e-01 -6.0266256e-04 -2.8420073e-01]
 [-1.4996020e+00 -4.9137783e-01 -1.6766689e+00 -6.5517044e-01]]


### Simple Generator Model With the Conv2DTranspose Layer

The Conv2DTranspose is more complex than the UpSampling2D layer, but it is also effective when used in GAN models, specifically the generator model. Either approach can be used, although the Conv2DTranspose layer is preferred, perhaps because of the simpler generator models and possibly better results, although GAN performance and skill is notoriously difficult to quantify.

In this case, our little GAN generator model must produce a 10 × 10 image and take a 100-element vector from the latent space as input, as in the previous UpSampling2D example.

First, a Dense fully connected layer can be used to interpret the input vector and create a sufficient number of activations (outputs) that can be reshaped into a low-resolution version of our output image, in this case, 128 versions of a 5 × 5 image.

Next, the 5 × 5 feature maps can be upsampled to a 10 × 10 feature map. We will use a 3 × 3 kernel size for the single filter, which will result in a slightly larger than doubled width and height in the output feature map (11 × 11). Therefore, we will set the padding argument to ‘same’ to ensure the output dimensions are 10 × 10 as required.

In [14]:
model = Sequential()

# define input shape, output enough activations for for 128 5x5 image
model.add(Dense(128 * 5 * 5, input_dim=100))

# reshape vector of activations into 128 feature maps with 5x5
model.add(Reshape((5, 5, 128)))

# double input from 128 5x5 to 1 10x10 feature map
model.add(Conv2DTranspose(1, (3, 3), strides=(2, 2), padding='SAME'))
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_7 (Conv2DTr (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


We can see that the Dense layer outputs 3,200 activations that are then reshaped into 128 feature maps with the shape 5 × 5. The widths and heights are doubled to 10 × 10 by the Conv2DTranspose layer resulting in a single feature map with quadruple the area.